[platformio]
default_envs = m5stick_c_plus

[env:m5stick_c_plus]
framework = espidf
platform = espressif32@6.9.0
board = m5stick-c
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
monitor_speed = 115200
build_flags =
  -DESPIDFORTH_ENABLE_TESTS=0
