[platformio]
default_envs = m5stick_c_plus
extra_configs = ../magnet-common.ini

[env:m5stick_c_plus]
extends = magnet_base
board = m5stick-c
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
