[platformio]
default_envs = xiao_s3

[env:xiao_s3]
; Seeed XIAO ESP32-S3 socketed onto the ReSpeaker Lite Voice Kit carrier.
; ESP32-S3 with 8 MB flash, no PSRAM. USB-C native serial-JTAG console.
framework = espidf
platform = espressif32@6.9.0
board = seeed_xiao_esp32s3
board_build.flash_mode = dio
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags =
  -DESPIDFORTH_ENABLE_TESTS=0
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
