[platformio]
default_envs = xiao_s3
extra_configs = ../magnet-common.ini

[env:xiao_s3]
; Seeed XIAO ESP32-S3 socketed onto the ReSpeaker Lite Voice Kit carrier.
; ESP32-S3 with 8 MB flash, no PSRAM. USB-C native serial-JTAG console.
extends = magnet_base
board = seeed_xiao_esp32s3
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
