[platformio]
default_envs = esp32s3

[env]
framework = espidf
platform = espressif32@6.9.0
monitor_speed = 115200

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.esp32s3"

[env:esp32c3]
board = esp32-c3-devkitc-02
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.esp32c3"

[env:esp32c6]
board = esp32-c6-devkitc-1
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.esp32c6"

[env:esp32]
board = esp32dev
