[platformio]
default_envs = esp32c3

[env:esp32c3]
framework = espidf
platform = espressif32@6.9.0
board = esp32-c3-devkitc-02
board_build.flash_mode = dio
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags =
  -DESPIDFORTH_ENABLE_TESTS=0
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
