[platformio]
default_envs = esp32c3
extra_configs = ../magnet-common.ini

[env:esp32c3]
extends = magnet_base
board = esp32-c3-devkitc-02
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
