#!/usr/bin/env python3
"""
bundles_to_header.py — build-time helper that emits a C header containing
each input bundle's JSON envelope as a string literal.

Why not EMBED_FILES? PlatformIO's IDF wrapper doesn't reliably track the
.S generation step CMake adds for EMBED_FILES, which fails the build with a
"Source not found" error. Inlining the bundles as string literals bypasses
the generation step entirely.

Usage:
    python bundles_to_header.py spawn.json scribe-extra.json \\
        > path/to/bundle_blobs.h
"""

import argparse
import json
import sys
from pathlib import Path


def c_escape(s: str) -> str:
    """Minimal C string-literal escape. Ample backslashes for \\, ", and
    newlines; everything else is left as UTF-8 bytes (gcc handles it)."""
    return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")


def sym(name: str) -> str:
    """Convert a bundle name like 'scribe-extra' to a C identifier."""
    return name.replace("-", "_").replace(".", "_")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+", help="Signed bundle .json files")
    ap.add_argument("--out", default="-", help="Output path (default stdout)")
    args = ap.parse_args()

    out_lines = [
        "// Auto-generated by scripts/bundles_to_header.py — DO NOT EDIT",
        "#ifndef BUNDLE_BLOBS_H",
        "#define BUNDLE_BLOBS_H",
        "",
    ]
    table = []
    for path in args.files:
        p = Path(path)
        try:
            content = p.read_text()
            json.loads(content)  # validate
        except Exception as e:
            print(f"{path}: not valid JSON: {e}", file=sys.stderr)
            return 2
        envelope = json.loads(content)
        name = envelope.get("name") or p.stem
        ident = sym(p.stem)
        out_lines.append(f"// {name} v{envelope.get('version','?')}")
        out_lines.append(f'static const char {ident}_json[] = "{c_escape(content)}";')
        table.append((name, ident))

    out_lines.append("")
    out_lines.append("typedef struct { const char *kv_key; const char *value; } bundle_blob_t;")
    out_lines.append("static const bundle_blob_t BUNDLE_BLOBS[] = {")
    for name, ident in table:
        out_lines.append(f'    {{ "bundle:{name}", {ident}_json }},')
    out_lines.append("};")
    out_lines.append("#define BUNDLE_BLOBS_COUNT (sizeof(BUNDLE_BLOBS)/sizeof(BUNDLE_BLOBS[0]))")
    out_lines.append("")
    out_lines.append("#endif")

    text = "\n".join(out_lines) + "\n"
    if args.out == "-":
        sys.stdout.write(text)
    else:
        Path(args.out).write_text(text)
        print(f"wrote {args.out} ({len(text)} bytes, {len(table)} bundles)",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
