// Auto-generated by scripts/bundles_to_header.py — DO NOT EDIT
#ifndef BUNDLE_BLOBS_H
#define BUNDLE_BLOBS_H

// spawn v0.1.0
static const char spawn_json[] = "{\n  \"name\": \"spawn\",\n  \"version\": \"0.1.0\",\n  \"min_proto\": 1,\n  \"author\": \"iotone-dev\",\n  \"caps_req\": [],\n  \"deps\": [],\n  \"crc32\": \"c3e64bab\",\n  \"sig_alg\": \"hmac-sha256\",\n  \"sig\": \"548525d92297affe55cdfd26cce8715951d9b804fe03a1e9dc1c0fb3e4678e24\",\n  \"src_b64\": \"XCBSb2xlOiBzcGF3biDigJQgbWluaW1hbCAiSSBqb2luZWQgdGhlIGhpdmUiIGlkZW50aXR5IGJ1bmRsZS4KXCBJbnN0YWxscyBhIHNpbmdsZSBncmVldGluZyB3b3JkIGFuZCBhbm5vdW5jZXMgaXRzZWxmIG9uY2UgYXQgaW5zdGFsbCB0aW1lLgpcIGNhcHNfcmVxOiBbXSAod29ya3Mgb24gYW55IG5vZGUpCgo6IGhlbGxvLXNwYXduIC4iIEhlbGxvIGZyb20gdGhlIHNwYXduIHJvbGUiIGNyIDsKaGVsbG8tc3Bhd24K\"\n}";
// scribe-extra v0.1.0
static const char scribe_extra_json[] = "{\n  \"name\": \"scribe-extra\",\n  \"version\": \"0.1.0\",\n  \"min_proto\": 1,\n  \"author\": \"iotone-dev\",\n  \"caps_req\": [\n    \"kv-store\"\n  ],\n  \"deps\": [],\n  \"crc32\": \"c833fb79\",\n  \"sig_alg\": \"hmac-sha256\",\n  \"sig\": \"9cc38a40236af22e6f6484185b710f9cdaeb1e4a6dca81b0a2a0300a6f883015\",\n  \"src_b64\": \"XCBSb2xlOiBzY3JpYmUtZXh0cmEg4oCUIGFkZHMgYSBjb3VwbGUgb2YgaGVscGVyIHdvcmRzIG9uIHRvcCBvZiB0aGUgYmFzZQpcIHNjcmliZS1zdG9yZSAvIHNjcmliZS1yZWNhbGwgdm9jYWJ1bGFyeSBhbHJlYWR5IHJlZ2lzdGVyZWQgYnkgdGhlIENhcHN1bGUKXCBmaXJtd2FyZS4gRGVtb25zdHJhdGVzIHRoYXQgYnVuZGxlcyBjYW4gZXh0ZW5kIEZGSSB3b3JkcyByYXRoZXIgdGhhbgpcIHJlcGxhY2UgdGhlbS4KXCBjYXBzX3JlcTogWyJrdi1zdG9yZSJdICAgKENhcHN1bGUgYWR2ZXJ0aXNlcyB0aGlzKQoKXCBQcmludCBhIGJhbm5lciB3aGVuZXZlciB0aGUgc2NyaWJlIGdyZWV0cyB0aGUgaGl2ZS4KOiBzY3JpYmUtYmFubmVyCiAgY3IgLiIgPT09IE1hZ05FVCBTY3JpYmUgcmVhZHkgPT09IiBjciA7CgpzY3JpYmUtYmFubmVyCg==\"\n}";
// spy-snapper v0.1.0
static const char spy_snapper_json[] = "{\n  \"name\": \"spy-snapper\",\n  \"version\": \"0.1.0\",\n  \"min_proto\": 1,\n  \"author\": \"iotone-dev\",\n  \"caps_req\": [\n    \"camera\"\n  ],\n  \"deps\": [],\n  \"crc32\": \"6bb4612a\",\n  \"sig_alg\": \"hmac-sha256\",\n  \"sig\": \"b633ca81818c187d541ff4900ab622599fb324a2615d54c9e4ea519564039384\",\n  \"src_b64\": \"XCBSb2xlOiBzcHktc25hcHBlciDigJQgc2luZ2xlLXNob3QgInRha2Ugb25lIHBpY3R1cmUiIHdvcmQgdGhhdCBhbiBleHRlcm5hbApcIHNjaGVkdWxlciBjYW4gaW52b2tlLiBSZWFsIHBlcmlvZGljLWNhcHR1cmUgbG9vcHMgc2hvdWxkIHVzZSBjb29wZXJhdGl2ZQpcIEZvcnRoIHRhc2tzIG9uY2UgdGhvc2UgbGFuZDsgZm9yIHYxIHdlIGtlZXAgaXQgYXMgYSBvbmUtc2hvdCBzbyB0aGUKXCBpbnN0YWxsIGRvZXNuJ3QgdGllIHVwIHRoZSBGb3J0aCBSRVBMLgpcIGNhcHNfcmVxOiBbImNhbWVyYSJdICAgKE01X0hpdmVfQ2FtZXJhIGFkdmVydGlzZXMgdGhpcykKCjogc25hcCAgIGNhbS1zbmFwIGRyb3AgOwoKXCBDb25maXJtIGluc3RhbGwgd2l0aCBvbmUgY2FwdHVyZSAoZHJvcCB0aGUgc2l6ZSBmcm9tIHRoZSBzdGFjaykuCnNuYXAK\"\n}";

typedef struct { const char *kv_key; const char *value; } bundle_blob_t;
static const bundle_blob_t BUNDLE_BLOBS[] = {
    { "bundle:spawn", spawn_json },
    { "bundle:scribe-extra", scribe_extra_json },
    { "bundle:spy-snapper", spy_snapper_json },
};
#define BUNDLE_BLOBS_COUNT (sizeof(BUNDLE_BLOBS)/sizeof(BUNDLE_BLOBS[0]))

#endif
