/*
 * bundle_bootstrap.c — pre-seed the ruler's in-memory KV table with the
 * starter bundles compiled into the firmware. Bundle envelope JSON is
 * embedded as C string literals via bundle_blobs.h, generated by
 * scripts/bundles_to_header.py. (We tried EMBED_FILES first, but
 * PlatformIO's IDF wrapper doesn't track the .S generation step
 * reliably and the build fails with "Source not found".)
 *
 * Adding a bundle:
 *   1. drop a .forth file in ../../bundles/
 *   2. sign it via scripts/sign_bundle.py → ../../bundles/<name>.json
 *   3. regenerate the companion header:
 *        python3 scripts/bundles_to_header.py bundles/[name].json
 *            --out M5StackDial-m5gfx-demo-ESPIDFORTH/src/bundle_blobs.h
 *   4. rebuild
 *
 * MIT License, Copyright (c) 2026 IoTone, Inc.
 */

#include "bundle_bootstrap.h"
#include "bundle_blobs.h"
#include <stddef.h>
#include "esp_log.h"
#include "craw_hive.h"

static const char *TAG = "bundle_bootstrap";

void bundle_bootstrap(void) {
    int seeded = 0;
    for (size_t i = 0; i < BUNDLE_BLOBS_COUNT; i++) {
        const bundle_blob_t *b = &BUNDLE_BLOBS[i];
        int rc = craw_hive_ruler_kv_put(b->kv_key, b->value);
        if (rc == 0) {
            ESP_LOGI(TAG, "seeded %s", b->kv_key);
            seeded++;
        } else {
            ESP_LOGW(TAG, "failed to seed %s rc=%d", b->kv_key, rc);
        }
    }
    ESP_LOGI(TAG, "bundle_bootstrap: %d / %d entries pre-loaded",
             seeded, (int)BUNDLE_BLOBS_COUNT);
}
