/**
 * UC6 shared network model — Kumamoto transit geometry + vehicle simulation.
 *
 * THREE-free on purpose (same rule as japanPrefectures.ts): imported by the
 * browser cell (`liveTransitSceneCell.ts`) for projection/rendering and by
 * the mock-join-server for the deterministic vehicle simulation, so it must
 * not pull renderer deps.
 *
 * The network snapshot itself lives in `public/maps/kumamoto-network.json`,
 * generated by `tools/fetch-kumamoto-network.mjs` from gtfs-data.jp (tram
 * CC BY 2.1 JP · buses CC BY 4.0). It is committed — no build-time network.
 */

/* ── snapshot types (mirror tools/fetch-kumamoto-network.mjs output) ── */

export type LonLat = [number, number];

export interface NetworkRoute {
  id: string;
  name: string;          // line code + variant, e.g. "O2-0"
  lines: LonLat[][];     // one or more polylines (MultiLineString parts)
  /** ALL GTFS route_ids folded into this line during variant dedupe —
   *  the GTFS-RT adapter maps live trip.routeIds back through these. */
  ids?: string[];
}

/** routeId → display line name, across every operator's variant ids. */
export function buildRouteNameIndex(net: KumamotoNetwork): Map<string, string> {
  const index = new Map<string, string>();
  for (const op of net.operators) {
    for (const r of op.routes) {
      for (const id of r.ids ?? [r.id]) index.set(id, r.name);
    }
  }
  return index;
}

export interface NetworkOperator {
  key: 'tram' | 'toshibus' | 'kumabus' | 'dentetsu' | string;
  kind: 'tram' | 'bus';
  nameJa: string;
  license: string;
  routes: NetworkRoute[];
  stops: LonLat[];
}

export interface KumamotoNetwork {
  generated: string;
  source: string;
  bbox: [number, number, number, number]; // minLon, minLat, maxLon, maxLat
  operators: NetworkOperator[];
}

/* ── projection — city-scale planar ─────────────────────────────────── */

/**
 * Equirectangular-with-cos(midLat) projection fitted to a bbox.
 * At Kumamoto's ~15 km extent the divergence from Mercator is far below
 * one screen pixel on a tabletop map, so no d3-geo dependency is needed.
 * Returns plane-local coords centered on the bbox: x east, y north, metres
 * scaled so the bbox's longer side equals `width`.
 */
export function makeCityProjection(bbox: [number, number, number, number], width: number) {
  const [minLon, minLat, maxLon, maxLat] = bbox;
  const midLat = (minLat + maxLat) / 2;
  const kx = Math.cos((midLat * Math.PI) / 180); // deg-lon shrink factor
  const spanX = (maxLon - minLon) * kx;
  const spanY = maxLat - minLat;
  const scale = width / Math.max(spanX, spanY);
  const cx = (minLon + maxLon) / 2;
  const cy = midLat;
  return {
    /** Map extents in plane units. */
    width: spanX * scale,
    height: spanY * scale,
    toXY(lon: number, lat: number): { x: number; y: number } {
      return { x: (lon - cx) * kx * scale, y: (lat - cy) * scale };
    },
  };
}

/* ── polyline walking (for the vehicle simulation) ──────────────────── */

const EARTH_M_PER_DEG_LAT = 111_320;

function segMeters(a: LonLat, b: LonLat): number {
  const kx = Math.cos(((a[1] + b[1]) / 2) * (Math.PI / 180));
  const dx = (b[0] - a[0]) * kx * EARTH_M_PER_DEG_LAT;
  const dy = (b[1] - a[1]) * EARTH_M_PER_DEG_LAT;
  return Math.hypot(dx, dy);
}

export function lineLengthMeters(line: LonLat[]): number {
  let m = 0;
  for (let i = 1; i < line.length; i++) m += segMeters(line[i - 1]!, line[i]!);
  return m;
}

/** Point + heading at `dist` metres along the polyline (clamped). */
export function pointAlong(line: LonLat[], dist: number): { lon: number; lat: number; bearing: number } {
  let remaining = Math.max(0, dist);
  for (let i = 1; i < line.length; i++) {
    const a = line[i - 1]!, b = line[i]!;
    const seg = segMeters(a, b);
    if (remaining <= seg && seg > 0) {
      const t = remaining / seg;
      const lon = a[0] + (b[0] - a[0]) * t;
      const lat = a[1] + (b[1] - a[1]) * t;
      const kx = Math.cos((lat * Math.PI) / 180);
      const bearing = (Math.atan2((b[0] - a[0]) * kx, b[1] - a[1]) * 180) / Math.PI;
      return { lon, lat, bearing: (bearing + 360) % 360 };
    }
    remaining -= seg;
  }
  const a = line[line.length - 2] ?? line[0]!;
  const b = line[line.length - 1]!;
  const kx = Math.cos((b[1] * Math.PI) / 180);
  const bearing = (Math.atan2((b[0] - a[0]) * kx, b[1] - a[1]) * 180) / Math.PI;
  return { lon: b[0], lat: b[1], bearing: (bearing + 360) % 360 };
}

/* ── vehicle payload (served by /api/v1/geo/kumamoto/vehicles) ──────── */

export interface TransitVehicle {
  id: string;
  op: string;          // operator key ('toshibus' | 'kumabus' | 'dentetsu')
  routeId: string;
  routeName: string;
  lat: number;
  lon: number;
  bearing: number;     // degrees clockwise from north
  ts: number;          // epoch ms of this position
}

export interface KumamotoVehiclesPayload {
  updated: string;
  source: 'gtfs-rt' | 'simulated';
  vehicles: TransitVehicle[];
}

/**
 * Deterministic simulated vehicles — buses only (the tram has no public
 * realtime feed; decision #4 renders it as static geometry). Per bus
 * operator, take the N longest route polylines and walk VEHICLES_PER_ROUTE
 * vehicles along each at city-bus speed, ping-ponging end↔end so nothing
 * teleports. Everything derives from wall clock → reproducible smoke
 * baselines, and adjacent polls advance smoothly.
 */
export function simulatedKumamotoVehicles(
  network: KumamotoNetwork,
  nowMs: number,
  opts: { routesPerOperator?: number; vehiclesPerRoute?: number; speedKmh?: number } = {},
): KumamotoVehiclesPayload {
  const routesPerOperator = opts.routesPerOperator ?? 4;
  const vehiclesPerRoute = opts.vehiclesPerRoute ?? 2;
  const speedMps = ((opts.speedKmh ?? 22) * 1000) / 3600;

  const vehicles: TransitVehicle[] = [];
  for (const op of network.operators) {
    if (op.kind !== 'bus') continue;
    const ranked = op.routes
      .map(r => {
        const line = r.lines.reduce((best, l) => (lineLengthMeters(l) > lineLengthMeters(best) ? l : best), r.lines[0]!);
        return { route: r, line, len: lineLengthMeters(line) };
      })
      .filter(r => r.len > 500)
      .sort((a, b) => b.len - a.len)
      .slice(0, routesPerOperator);

    ranked.forEach(({ route, line, len }, ri) => {
      for (let vi = 0; vi < vehiclesPerRoute; vi++) {
        // Phase-offset each vehicle so they spread along the route; the
        // ping-pong period is 2×len at speedMps.
        const phase = ((ri * 7919 + vi * 104729) % 1000) / 1000; // deterministic
        const travelled = nowMs / 1000 * speedMps + phase * 2 * len;
        const cycle = travelled % (2 * len);
        const forward = cycle <= len;
        const dist = forward ? cycle : 2 * len - cycle;
        const p = pointAlong(line, dist);
        vehicles.push({
          id: `${op.key}-${route.id}-${vi}`,
          op: op.key,
          routeId: route.id,
          routeName: route.name,
          lat: p.lat,
          lon: p.lon,
          bearing: forward ? p.bearing : (p.bearing + 180) % 360,
          ts: nowMs,
        });
      }
    });
  }
  return { updated: new Date(nowMs).toISOString(), source: 'simulated', vehicles };
}
