/**
 * Shared text styling for the chrome layer (Toolbar, PrivacyBanner, etc.).
 *
 * We use three-mesh-ui's MSDF text instead of troika-three-text for any text
 * rendered inside a ThreeMeshUI.Block, because:
 *   - MSDF gives sharp edges at every distance/scale/angle without per-instance
 *     tuning — the antialiasing demo at https://felixmariotto.github.io/three-mesh-ui/#antialiasing
 *     shows the same glyph readable from across the room and from 30 cm away.
 *   - Layout is parent-driven: setting `fontFamily`/`fontTexture` on a parent
 *     Block means every Text descendant inherits it, so we don't sprinkle the
 *     font URL through 7+ component files.
 *
 * Caveat: the bundled Roboto-msdf only covers ~223 chars (Basic Latin + a slice
 * of Latin-1). Glyphs outside the set (middle dot, em dash, arrows, emoji)
 * throw inside three-mesh-ui's MSDFGlyph constructor and take down the scene.
 * `sanitizeText()` below maps the common offenders to ASCII fallbacks; pass
 * dynamic strings (manifest labels, status messages, etc.) through it before
 * handing them to ThreeMeshUI.Text.
 *
 * Mark/chart labels (in src/viz/**) still use troika because their text lives
 * on bare THREE.Group hierarchies, not inside Blocks. A future pass can either
 * wrap those in Blocks or tune troika's sdfGlyphSize/outlineWidth on the
 * viz layer specifically.
 */
import * as THREE from 'three';
import ThreeMeshUI from 'three-mesh-ui';

/** Public-served paths — Vite copies anything under `public/` to the dist root. */
export const FONT_FAMILY_URL = '/fonts/Roboto-msdf.json';
export const FONT_TEXTURE_URL = '/fonts/Roboto-msdf.png';

/**
 * Block options every chrome Block should spread in so its Text children
 * find the MSDF atlas. Stripped of layout opinions on purpose — each caller
 * still owns its own width/height/justifyContent/etc.
 *
 * Apply it on *every* Block, not just roots: three-mesh-ui's font lookup
 * walks up the `parentUI` chain, but defensive declaration is cheaper than
 * debugging "no font was found" warnings on intermediate slot Blocks.
 */
export const FONT_BLOCK_OPTS = {
  fontFamily: FONT_FAMILY_URL,
  fontTexture: FONT_TEXTURE_URL,
} as const;

/**
 * Convert a `number` color (hex int from `palette.ts`) into the
 * `THREE.Color` instance ThreeMeshUI expects on `fontColor`.
 *
 * Inlined here rather than importing from three so callers can pass our
 * palette values directly without re-instantiating Color at every call site.
 */
export function fontColor(hex: number): THREE.Color {
  return new THREE.Color(hex);
}

/**
 * Charset actually present in the bundled `/fonts/Roboto-msdf.json`.
 *
 * The file ships with three-mesh-ui's examples and is a multilingual sampler
 * (Latin letters + digits + Cyrillic + Greek + Scandi + a curated punctuation
 * subset) — it is NOT a full ASCII font. `^`, `<`, `>`, `` ` ``, etc. are all
 * absent. Anything outside this set crashes inside MSDFGlyph.mapUVs with
 * "Cannot read properties of undefined (reading 'x')".
 *
 * Generated by enumerating `font.info.charset` once; hardcoded here so the
 * sanitizer doesn't pay a JSON fetch on every text update. If we ever swap
 * the bundled font for a richer MSDF, regenerate this set.
 */
const FONT_SUPPORTED_CHARS = new Set<string>([
  // Letters (lower + upper)
  ...'abcdefghijklmnopqrstuvwxyz',
  ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  // Digits
  ...'0123456789',
  // Punctuation actually present in the bundled atlas — verified by reading
  // info.charset; missing: ^ < > ` (don't add to static UI strings).
  ...'/\\*-+,;:!?.%$=&~"\'#_|@()[]{}',
  '£', '€', '°', '–',                  // bundled extended punctuation
  // Whitespace is handled separately by MSDFGlyph (no UV lookup needed).
  ' ', '\t', '\n',
]);

/**
 * Map of unsupported-but-common characters to fallbacks the bundled font
 * actually carries. Keep entries here when adding new dynamic content —
 * if you see a unicode glyph crash the scene, add it here.
 */
const CHAR_FALLBACKS: Record<string, string> = {
  '·': '-',      // middle dot ·    — common in our subtitles
  '—': '--',     // em dash —       — used in privacy banner body
  '‘': "'",      // left single quote
  '’': "'",      // right single quote
  '“': '"',      // left double quote
  '”': '"',      // right double quote
  '•': '*',      // bullet
  '…': '...',    // ellipsis
  '→': '->',     // right arrow → ('->' is two safe chars, '>'-alone is NOT safe)
  '←': '<-',     // left arrow (note: '<' isn't supported, but '<-' renders fine
                 // because the fallback is interpreted char-by-char — both '-'
                 // is safe; the '<' inside this *fallback string* would still
                 // crash, so it's actually replaced below)
  '✓': '+',      // check
  '✗': 'x',      // cross
  '×': 'x',      // multiplication sign
  '>': '/',      // ASCII gt — bundled font lacks it; use slash for breadcrumbs
  '<': '/',      // ASCII lt — same problem
  '^': '+',      // ASCII caret — bundled font lacks it (used for up-arrow)
  '`': "'",      // ASCII backtick
};

// Re-fix `<-` so the fallback string itself is safe.
CHAR_FALLBACKS['←'] = '-';

/**
 * Replace or strip characters the bundled MSDF atlas can't render. Pass any
 * dynamic string through this before handing it to `new ThreeMeshUI.Text` or
 * `.set({ content })`. Per-character substitution: each char is checked
 * against `FONT_SUPPORTED_CHARS`; if unsupported it's replaced via
 * `CHAR_FALLBACKS` or dropped.
 *
 * Static strings in this codebase should be written using only chars in the
 * supported set — but sanitize is cheap and idempotent, so wrapping
 * everything defensively keeps the UI robust to manifest-supplied content.
 */
export function sanitizeText(s: string): string {
  let out = '';
  for (const ch of s) {
    if (FONT_SUPPORTED_CHARS.has(ch)) {
      out += ch;
    } else if (CHAR_FALLBACKS[ch] !== undefined) {
      out += CHAR_FALLBACKS[ch];
    }
    // Else: drop silently. Logging would be too noisy; the visual gap is the
    // signal that we need to add a fallback or upgrade the font.
  }
  return out;
}

/**
 * Invisible transparent Block sized to a specific slot in the parent's
 * absolute layout — convenient when porting troika-positioned text to MSDF.
 * Each slot is a fully-configured Block (with the font attached) so its
 * Text child doesn't depend on font inheritance walking through an ancestor.
 */
export function makeSlot(
  width: number,
  height: number,
  opts: { align?: 'center' | 'start' | 'end'; textAlign?: 'center' | 'left' | 'right' } = {},
): InstanceType<typeof ThreeMeshUI.Block> {
  return new ThreeMeshUI.Block({
    ...FONT_BLOCK_OPTS,
    width, height,
    backgroundOpacity: 0,
    borderOpacity: 0,
    justifyContent: 'center',
    alignItems: opts.align ?? 'center',
    textAlign: opts.textAlign ?? 'center',
  });
}
