[platformio]
default_envs = m5capsule

[env:m5capsule]
; M5Capsule — ESP32-S3FN8 (8 MB flash, no PSRAM), USB-C native serial-JTAG.
framework = espidf
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags =
  -DESPIDFORTH_ENABLE_TESTS=0
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
