[platformio]
default_envs = m5capsule
extra_configs = ../magnet-common.ini

[env:m5capsule]
; M5Capsule — ESP32-S3FN8 (8 MB flash, no PSRAM), USB-C native serial-JTAG.
extends = magnet_base
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_build.cmake_extra_args =
  -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
