[platformio]
default_envs = esp32s3
extra_configs = ../magnet-common.ini

[env:esp32s3]
extends = magnet_base
board = adafruit_feather_esp32s3_nopsram
board_build.flash_mode = dio
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB
